---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: kubetoy-channel-route
  namespace: kubetoy-channel-namespace
  labels:
    app: kubetoy-app
spec:
  template:
    kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: kubetoy
      labels:
        app: kubetoy-app
    spec:
      subdomain: ''
      to:
        kind: Service
        name: kubetoy-service
        weight: 100
      port:
        targetPort: http
      wildcardPolicy: None