---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: kubetoy-channel-service
  namespace:  kubetoy-channel-namespace
  labels:
    app: kubetoy-app
spec:
  template:
    apiVersion: v1
    kind: Service
    metadata:
      name: kubetoy-service
      labels:
        app: kubetoy-app
    spec:
      type: ClusterIP
      ports:
        - targetPort: 3000
          port: 3000
          protocol: TCP
          name: "http"
      selector:
        app: kubetoy