---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: kubetoy-channel-deployment
  namespace: kubetoy-channel-namespace
  labels:
    app: kubetoy-app
spec:
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: kubetoy-channel-deployment
      labels:
        app: kubetoy-app
    spec:
        selector:
          matchLabels:
            app: kubetoy
        template:
          metadata:
            labels:
              app: kubetoy
          spec:
            containers:
            - name: kubetoy
              image: docker.io/ibmicpcoc/kubetoy:latest
              imagePullPolicy: Always
              ports:
              - containerPort: 3000
              volumeMounts:
              - name: configvol
                mountPath: /var/config
              - name: secretvol
                mountPath: /var/secret
              livenessProbe:
                httpGet:
                  path: /health
                  port: 3000
                initialDelaySeconds: 10
                periodSeconds: 5
              requests:
                memory: "5Mi"
                cpu: "1m"
              limits:
                memory: "20Mi"
                cpu: "2m"
              env:
              - name: ENV_TOY_CONFIGMAP
                valueFrom: 
                  configMapKeyRef:
                    name: kubetoy-configmap-env
                    key: ENV_TOY_CONFIGMAP
              - name: ENV_TOY_SECRET
                valueFrom:
                  secretKeyRef:
                    name: kubetoy-secret-env
                    key: ENV_TOY_SECRET
            volumes:
            - name: configvol
              configMap:
                name: kubetoy-configmap-files
            - name: secretvol
              secret:
                secretName: kubetoy-secret-files