---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: kubetoy-channel-cm-env
  namespace: kubetoy-channel-namespace
  labels:
    app: kubetoy-app
spec:
  template:
    spec: {}
    kind: ConfigMap
    apiVersion: v1
    metadata:
      name: kubetoy-configmap-env
    data:
      ENV_TOY_CONFIGMAP: 'This is a configuration value.'