---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: kubetoy-channel-sec-file
  namespace: kubetoy-channel-namespace
  labels:
    app: kubetoy-app
spec:
  template:
    spec: {}
    apiVersion: v1
    kind: Secret
    metadata:
      name: kubetoy-secret-files
    type: Opaque
    data:
      toy-secret.txt: U2hoLi4uIFRoaXMgaXMgYSBzZWNyZXQu
      